module.exports = {
    personal: [
        { name: "pancard", maxCount: 1 },
        { name: "adharcard", maxCount: 1 },
        { name: "salarySlips", maxCount: 3 },
        { name: "bankStatements", maxCount: 12 },
        { name: "photo", maxCount: 1 },
        { name: "form16", maxCount: 1 },
        { name: "offerLetter", maxCount: 1 },
        { name: "cibilReport", maxCount: 1 },
    ],
    home: [
        { name: "pancard", maxCount: 1 },
        { name: "adharcard", maxCount: 1 },
        { name: "salarySlips", maxCount: 3 },
        { name: "form16", maxCount: 1 },
        { name: "photo", maxCount: 1 },
        { name: "bankStatements", maxCount: 12 },
        { name: "propertyDocs", maxCount: 5 },
    ],
    business: [
        { name: "pancard", maxCount: 1 },
        { name: "adharcard", maxCount: 1 },
        { name: "photo", maxCount: 1 },
        { name: "salarySlips", maxCount: 3 },
        { name: "form16", maxCount: 1 },
        { name: "bankStatements", maxCount: 12 },
        { name: "gstReturn", maxCount: 3 },
        { name: "itrDocs", maxCount: 3 },
    ],
    mortgage: [
        { name: "pancard", maxCount: 1 },
        { name: "adharcard", maxCount: 1 },
        { name: "photo", maxCount: 1 },
        { name: "propertyDocs", maxCount: 5 },
        { name: "loanSanctionLetter", maxCount: 1 },
    ],
};
